# Bug in 7.3 only with phpunit and xdebug causes segfault 11 so xdebug disabled for 7.3
language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot
dist: xenial
env:
  matrix:
    - DB_ENGINE=mysql DB_HOST=localhost DB_USERNAME=root
    - DB_ENGINE=pgsql DB_HOST=localhost DB_USERNAME=postgres
  include:
      - php: 7.2
        env: COVERAGE=true
services:
  - mysql
  - postgresql
before_install:
  - if [ $DB_ENGINE = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE commands;'; fi
  - if [ $DB_ENGINE = 'pgsql' ]; then psql -c 'CREATE DATABASE commands;' -U postgres; fi
before_script:
  - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi
  - composer install --prefer-source --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
after_script:
   - |
      if [[ $COVERAGE == true ]]; then
        vendor/bin/phpunit --coverage-clover coverage.xml
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        php php-coveralls.phar --verbose
      fi
cache:
  directories:
    - $HOME/.composer/cache/files